### ISSUE TITLE
[Documentation Versioning] latest version of docs does not match installer

### ISSUE THREAD

**Issue by susanmulcahy** [ove/ove-docs#15] opened 2018-12-05 18:41 UTC
this can be solved by versioning the documentation

**Comment by senakafdo** [comment] 2018-12-06 02:31
The issues with the current installer has been fixed in ove/ove-install@af533d6. However, we still need to version the docs and then update the installer to respect such a versioning format, which we do not have as yet.

**Comment by oserban** [comment] 2018-12-06 11:44
The issue is with the documentation version. I personally think this is a terrible practice to advise people to install latest-unstable as their default version. Reverted the install scripts to a stable version and we'll need to figure out documentation versioning.

**Closed as completed** 2019-02-11 03:30 UTC
Labels: enhancement, documentation
